// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:2f9b19a6-536f-4265-8bd2-c1919a3bd9a9",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_CRiR7oUBe",
    "aws_user_pools_web_client_id": "6p119k8e1o96spj0m64db6ru1f",
    "oauth": {}
};


export default awsmobile;
